acme_phpdish_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: AcmePHPDishExamplePlugin:Greeting:staticallyGreet
        name: ~

acme_phpdish_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: AcmePHPDishExamplePlugin:Greeting:dynamicallyGreet
        name: ~
